version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "08:00"
      timezone: "Asia/Tokyo"
    groups:
      astro:
        patterns:
          - "astro"
      tailwind:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "08:00"
      timezone: "Asia/Tokyo"
